"""Create simaenaga_lines table

Revision ID: b71eac6b3d17
Revises: cbe481ee3e1f
Create Date: 2025-04-25 05:04:12.965272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71eac6b3d17'
down_revision: Union[str, None] = 'cbe481ee3e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simaenaga_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simaenaga_lines_id'), 'simaenaga_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simaenaga_lines_id'), table_name='simaenaga_lines')
    op.drop_table('simaenaga_lines')
    # ### end Alembic commands ###
