"""drop elo rating column

Revision ID: 23fedc8164e2
Revises: 50c1faa4252f
Create Date: 2025-04-21 07:13:14.818129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fedc8164e2'
down_revision: Union[str, None] = '50c1faa4252f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'options',
        sa.Column('trueskill_mu', sa.Float(), nullable=False, server_default='25.0'),
    )
    op.add_column(
        'options',
        sa.Column('trueskill_sigma', sa.Float(), nullable=False, server_default='8.3333333333'),
    )
    op.alter_column('options', 'trueskill_mu',    server_default=None)
    op.alter_column('options', 'trueskill_sigma', server_default=None)
    op.drop_column('options', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('options', 'trueskill_sigma')
    op.drop_column('options', 'trueskill_mu')
    # ### end Alembic commands ###
