"""change_option

Revision ID: ed2456a72ff8
Revises: 3ab377645da9
Create Date: 2025-04-10 09:30:57.479938
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed2456a72ff8'
down_revision: Union[str, None] = '3ab377645da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to avoid duplicate columns ###
    op.alter_column('options', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('options', 'label',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('options', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('options', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('options_theme_id_fkey', 'options', type_='foreignkey')
    op.create_foreign_key(None, 'options', 'themes', ['theme_id'], ['id'], ondelete='CASCADE')
    # Removed: op.drop_column('options', 'times_compared')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted accordingly ###
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.create_foreign_key('options_theme_id_fkey', 'options', 'themes', ['theme_id'], ['id'])
    op.alter_column('options', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('options', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('options', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('options', 'label',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('options', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # Removed: op.add_column('options', sa.Column('times_compared', ...))
    # ### end Alembic commands ###
