"""add comparison table

Revision ID: 5a806f5a625a
Revises: ed2456a72ff8
Create Date: 2025-04-10 09:43:24.259861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a806f5a625a'
down_revision: Union[str, None] = 'ed2456a72ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('option1_id', sa.Integer(), nullable=False),
    sa.Column('option2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option1_id'], ['options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option2_id'], ['options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'theme_id', 'option1_id', 'option2_id', name='uq_session_comparison')
    )
    op.create_index(op.f('ix_comparison_id'), 'comparison', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparison_id'), table_name='comparison')
    op.drop_table('comparison')
    # ### end Alembic commands ###
