"""create votes table

Revision ID: 5e0500673eaa
Revises: cf118a337e4d
Create Date: 2025-04-24 08:15:35.877383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0500673eaa'
down_revision: Union[str, None] = 'cf118a337e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'votes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'user_id',
            sa.Integer(),
            nullable=True,  # ログイン不要にするため nullable=True
        ),
        sa.Column('theme_id', sa.Integer(), nullable=False),
        sa.Column('winner_option_id', sa.Integer(), nullable=False),
        sa.Column('loser_option_id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['theme_id'], ['themes.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['winner_option_id'], ['options.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['loser_option_id'], ['options.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###
