"""Add label column to themes

Revision ID: 8b72461d1176
Revises: ded83ba53f0a
Create Date: 2025-04-09 12:01:19.825168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b72461d1176'
down_revision: Union[str, None] = 'ded83ba53f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'label')
    # ### end Alembic commands ###
